# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools requests
        python setup.py bdist_wheel sdist
        python setup.py install
    - name: Test
      run: |
        echo '{"env0": "str"}' > system_params.json
        python examples/main.py > log || true
        python tests/pseudo_unit_tests.py

        # test -no option
        python examples/main.py -no > log || true
        python tests/pseudo_unit_tests.py -no

        # test -p option
        rm system_params.json
        echo '{"env0": "str"}' > sys.json
        python examples/main.py -p sys.json > log || true
        python tests/pseudo_unit_tests.py

        python3 examples/main_http.py
